chore: add migrations and seeders files
Daskom-Lab/daskomrec23 pull request #3
Opened 2023-02-06 11:06 UTC by adamwisnup

create table migrations admins, assistantcontacts, datacaas, passcheck, passcheckmessages, plotactives, plots, shifts, stagenames, stages, statuses, statusstages and edit DatabaseSeeder

2023-02-08 07:42 UTC, adhiiimf commented
First, before i review your `PR` about Backend. I want to see DB Relation with illustration like this or something relate
![image](https://user-images.githubusercontent.com/66113867/217465570-468eee91-24f5-4d41-a2c8-21b7ff4117a5.png)
@adamwisnup

2023-02-08 08:25 UTC, adamwisnup commented
DB relation that I have created and migrated to table
<img width="880" alt="DB-Daskomrec23" src="https://user-images.githubusercontent.com/90138088/217474010-53ebfc1d-e5fb-400b-9aa6-f89bfd358981.png">
@adhiiimf

2023-02-08 10:04 UTC, adhiiimf commented
> DB relation that I have created and migrated to table <img alt="image" width="869" src="https://user-images.githubusercontent.com/90138088/217475656-ab1b84a1-599b-4936-9b66-0c1295e937ce.png"> @adhiiimf

**1. saran dari saya, ini tambahin column nama dan kelas (kalau perlu no. hp juga gapapa bebas)**
![image](https://user-images.githubusercontent.com/66113867/217495731-03ee3fc8-2e3f-4245-a06f-8cd36bfa63f4.png)

![image](https://user-images.githubusercontent.com/66113867/217498051-08f1a22c-1cd1-4c58-af37-60c3e6b8d6a6.png)
dan itu, boleh dijelasin gak dam maksud dari relasi itu?

![image](https://user-images.githubusercontent.com/66113867/217498189-414376e9-bb15-4685-ad12-88898fa6b6a8.png)
dan ini juga, perbedaan `statusstages` sama `stages` itu buat apa ya? dan kenapa relasinya dari `statusstages` ke `stagesname` bukan sebaliknya?

2023-02-08 13:03 UTC, adamwisnup commented
1. oke bang nanti saya tambahin buat datacaasnya
2.  seblumnya saya mau ngasih tau dulu bang ini tabel yang saya buat saya make referensi dari repository web recruitment tahun lalu, jadi kalo tabel itu di plotactive dia bakalan aktifin plotongan harusnya bang dia ngambil relasinya dari id_datacaas
3.  jadi tabel stages itu relasi sama status yang bakal ngasih tau buat caas ini lolos apa enggaknya, terus di tabel stagesname dia berisikan semua nama tahap rekrutmenya relasinya ke tabel statusstages itu bakalan dari nama tahap yang ada yang tahap sedang di laksanakan itu apa

> > DB relation that I have created and migrated to table <img alt="image" width="869" src="https://user-images.githubusercontent.com/90138088/217475656-ab1b84a1-599b-4936-9b66-0c1295e937ce.png"> @adhiiimf
> 
> **1. saran dari saya, ini tambahin column nama dan kelas (kalau perlu no. hp juga gapapa bebas)** ![image](https://user-images.githubusercontent.com/66113867/217495731-03ee3fc8-2e3f-4245-a06f-8cd36bfa63f4.png)
> 
> ![image](https://user-images.githubusercontent.com/66113867/217498051-08f1a22c-1cd1-4c58-af37-60c3e6b8d6a6.png) dan itu, boleh dijelasin gak dam maksud dari relasi itu?
> 
> ![image](https://user-images.githubusercontent.com/66113867/217498189-414376e9-bb15-4685-ad12-88898fa6b6a8.png) dan ini juga, perbedaan `statusstages` sama `stages` itu buat apa ya? dan kenapa relasinya dari `statusstages` ke `stagesname` bukan sebaliknya?

2023-02-08 13:23 UTC, adhiiimf commented
> > > DB relation that I have created and migrated to table <img alt="image" width="869" src="https://user-images.githubusercontent.com/90138088/217475656-ab1b84a1-599b-4936-9b66-0c1295e937ce.png"> @adhiiimf
> > 
> > 
> > **1. saran dari saya, ini tambahin column nama dan kelas (kalau perlu no. hp juga gapapa bebas)** ![image](https://user-images.githubusercontent.com/66113867/217495731-03ee3fc8-2e3f-4245-a06f-8cd36bfa63f4.png)
> > ![image](https://user-images.githubusercontent.com/66113867/217498051-08f1a22c-1cd1-4c58-af37-60c3e6b8d6a6.png) dan itu, boleh dijelasin gak dam maksud dari relasi itu?
> > ![image](https://user-images.githubusercontent.com/66113867/217498189-414376e9-bb15-4685-ad12-88898fa6b6a8.png) dan ini juga, perbedaan `statusstages` sama `stages` itu buat apa ya? dan kenapa relasinya dari `statusstages` ke `stagesname` bukan sebaliknya?
> 
> 1. oke bang nanti saya tambahin buat datacaasnya
> 2. seblumnya saya mau ngasih tau dulu bang ini tabel yang saya buat saya make referensi dari repository web recruitment tahun lalu, jadi kalo tabel itu di plotactive dia bakalan aktifin plotongan harusnya bang dia ngambil relasinya dari id_datacaas
> 3. jadi tabel stages itu relasi sama status yang bakal ngasih tau buat caas ini lolos apa enggaknya, terus di tabel stagesname dia berisikan semua nama tahap rekrutmenya relasinya ke tabel statusstages itu bakalan dari nama tahap yang ada yang tahap sedang di laksanakan itu apa

wkwkw yap pantes familliar relasinya, karena tahun lalu itu kl gasalah DB nya gaada diubah sama sekali (masih dr tahun saya)
nah okee no problem sebenernya, menurut saya di poin `3`, itu dari 3 tabel bisa dijadiin 2 tabel aja wkwkwk coba dipikirin gimana relasinya

2023-02-08 13:52 UTC, adhiiimf requested changes
overall good buat kamu yang baru coba buat migrations dan seeder nya, paling ada beberapa komentar ya biar kedepannya lebih oke lagi 😁

2023-02-08 13:52 UTC, adhiiimf commented on database/migrations/2023_02_06_104013_create_datacaas_table.php
> +            $table->timestamps();
okey ini yang diupdate data2nya ya, ternyata disini udah ada column nama, tinggal kelas tambahin sama yg lain kalau mau juga (bebas)

2023-02-08 13:52 UTC, adhiiimf commented on database/migrations/2023_02_06_104832_create_assistantcontacts_table.php
> +};
coba dicek lagi ini, tabel ini harusnya bukan itu kan isi2nya wkwkwk

2023-02-08 13:52 UTC, adhiiimf commented on database/migrations/2023_02_06_104026_create_statuses_table.php
> +            $table->boolean('isPass');
ini di ilustrasi namanya isLolos ya? nah kalau bisa konsisten biar gabingung wwkwk

2023-02-08 13:52 UTC, adhiiimf commented on database/seeders/DatabaseSeeder.php
> +        ]);
oke biar sekalian, ini buat file masing2 aja ya dam

2023-02-12 18:14 UTC, adhiiimf approved these changes

2023-02-12 18:30 UTC, merged