chore: add Models
Daskom-Lab/daskomrec23 pull request #5
Opened 2023-02-11 15:27 UTC by vincentiusantu

Creating Models

2023-02-12 18:15 UTC, adhiiimf requested changes
okey, coba sinkronkan lagi dengan tabel yang dibuat oleh adam, karena tadi ada 1 yang kelewat, sisanya aman

2023-02-12 18:15 UTC, adhiiimf commented on app/Models/DataCaas.php
> +        'password',
ada yang lupa nih, `nama`, tolong diupdate ya

2023-02-12 20:09 UTC, vincentiusantu commented on app/Models/DataCaas.php
> +        'password',
done bang, dan udah saya cek ulang file model yang lainnya bang, aman

2023-02-13 02:41 UTC, adhiiimf approved these changes
Nice, oke saya approved

2023-02-13 06:45 UTC, merged